import tkinter as tk
window = tk.Tk()
uname_label = tk.Label(text = "Username", width=80)
passw_label = tk.Label(text = "Password", width=80)
btn = tk.Button(text="Submit", width=10, bg='gray')
uname_entry = tk.Entry()
passw_entry = tk.Entry()
uname_label.pack()
uname_entry.pack()
passw_label.pack()
passw_entry.pack()
btn.pack()
uname = uname_entry.get()
passw = passw_entry.get()
window.mainloop()